# swees <stellarpay2.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
]

[DOCUMENTATION]
ORG_NAME="stellarpay2"
ORG_URL="https://stellarpay2.github.io/"
ORG_LOGO ="https://stellarpay2.github.io/img/crown.png"
ORG_OFFICIAL_EMAIL="stellarpay2@proton.me"
ORG_SUPPORT_EMAIL="stellarpay2@proton.me"
ORG_DESCRIPTION=": POWER BUY SWEESSCUTODY"

[[PRINCIPALS]]
email="non"

[[CURRENCIES]]
code ="CROWN"
name ="CROWN"
issuer = "GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://stellarpay2.github.io/img/crown.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000


[[CURRENCIES]]
code ="SGB"
name ="SWEES GOLD BOND"
issuer = "GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://stellarpay2.github.io/img/SGB.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code ="BTC"
name ="BTC"
issuer = "GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://stellarpay2.github.io/img/BTC.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code ="LOCK"
name ="MAKER KAY"
issuer = "GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://stellarpay2.github.io/img/Kay.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code="CHATBOT"
name="Chat"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="ChatGPT"
image="https://stellarpay2.github.io/img/chat.png"
status="live"

[[CURRENCIES]]
code ="USD"
name ="UNITED STET BOND"
issuer = "GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://stellarpay2.github.io/img/USD.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code="XAU"
name="SWEES GOLD"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="GolD"
image="https://stellarpay2.github.io/img/SGB.png"
status="live"



[[CURRENCIES]]
code="ROLL"
name="Received "
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Received of customers"
image="https://stellarpay2.github.io/img/RECO.png"
status="live"


[[CURRENCIES]]
code="LOGO"
name="LOGO"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="BOSS"
image="https://stellarpay2.github.io/img/BOSS.png"
status="live"


[[CURRENCIES]]
code="VFX"
name="VFX"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="BOND"
image="https://stellarpay2.github.io/img/BOND.png"
status="live"


[[CURRENCIES]]
code="TERA"
name="TERA"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="T"
image="https://stellarpay2.github.io/img/T.png"
status="live"



[[CURRENCIES]]
code="MG100"
name="MG100"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="1oo"
image="https://stellarpay2.github.io/img/100.png"
status="live"


[[CURRENCIES]]
code="QXLM"
name="1X1 WITH XLM"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Q"
image="https://stellarpay2.github.io/img/Q.png"
status="live"



[[CURRENCIES]]
code="RIGHT"
name="RIGHT"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="Yes"
image="https://stellarpay2.github.io/img/YES.png"
status="live"

[[CURRENCIES]]
code ="USA"
name ="UNIT OF USDT"
issuer = "GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://stellarpay2.github.io/img/USD.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000




[[CURRENCIES]]
code="BULL"
name="S&P500"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="SNP500"
image="https://stellarpay2.github.io/img/SNP.png"
status="live"


[[CURRENCIES]]
code="DW"
name="DISCOWAR WOLD"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="DW"
image="https://stellarpay2.github.io/img/DW.png"
status="live"



[[CURRENCIES]]
code="DOLLAR"
name="FOR YOU"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="dex"
image="https://stellarpay2.github.io/img/DEX.png"
status="live"



[[CURRENCIES]]
code="POK"
name="Pakistani RUPPY"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="POK"
image="https://stellarpay2.github.io/img/POK.png"
status="live"


[[CURRENCIES]]
code="MBA"
name="MASTAR"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="MASTAR"
image="https://stellarpay2.github.io/img/MBA.png"
status="live"



[[CURRENCIES]]
code="GDDSX"
name="GDDSX"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="ALL"
image="https://stellarpay2.github.io/img/STAR.png"
status="live"


[[CURRENCIES]]
code="WALLET"
name="wallet for reword"
issuer="GC7JONJXXXVADWPKGIOERWUHFVCO5KEWMVRFI742IPEIXBKPVTD3WBPZ"
is_asset_anchored=false
anchor_asset_type="other"
anchor_asset="wallet"
image="https://stellarpay2.github.io/img/wallet.png"
status="live"



